# Generated by Django 4.0.6 on 2023-09-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
